
# This is for development

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  leetcode-api:
    image: alfaarghya/alfa-leetcode-api:2.0.1
    ports:
      - "3000:3000"

volumes:
  redis_data: